In [1]:
%pylab inline
%load_ext autoreload
%autoreload 2
import sys
sys.path.insert(0,'../..')
import omama as O

Populating the interactive namespace from numpy and matplotlib


In [2]:
odl = O.OutlierDetectorLite()

In [3]:
imgs = odl.load_data('ASTAR')

In [4]:
feat_vect = O.Features.get_features(imgs, 'hist', 'gaussian', timing=False, sigma=1)

In [5]:
feat_vect

[array([2322867,    7940,    9064,  136859, 1913985,       1], dtype=uint32),
 array([4245700,   25502,  316468, 2690742,   52015,       1], dtype=uint32),
 array([3171397,   17507,   34324,  918235,  249230,      23], dtype=uint32),
 array([2757690,   18147,   13344, 1210413,  391121,       1], dtype=uint32),
 array([3065154,   21171,   21557, 1118881,  163952,       1], dtype=uint32),
 array([5321400,   43740,   21134, 1868515,   75638,       1], dtype=uint32),
 array([3178362,   16926,   39389, 3454330,  641420,       1], dtype=uint32),
 array([2405007,   15505,   73133, 1795688,  101331,      52], dtype=uint32),
 array([3976147,   26162,   80333, 2996594,  251191,       1], dtype=uint32),
 array([4934639,   16147,   21181, 1965113,  393347,       1], dtype=uint32),
 array([3528201,   17204,   49427, 2759430,  976165,       1], dtype=uint32),
 array([2915026,   14195,   23777, 1414582,   23135,       1], dtype=uint32),
 array([10478662,  2076316,   872329,   127665,    76355,      1