In [1]:
%pylab inline
%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib


In [2]:
import sys
sys.path.insert(0,'../..')
import omama as O
from types import SimpleNamespace

In [3]:
dataset = "A"
if dataset == 1 or dataset == "A":
    print(f'populating dataset with 8% errors...')


populating dataset with 8% errors...


In [4]:
images = [[1],[1,2,3,4,5],[5,4,3,2,5,3,4],[3,4],[8,8,8],[1,0,2,93,4,5],[5,8,7,3]]
train_scores = [1,5,7,2,3,6,4]

In [5]:
images_list = []
for i in range(len(images)):
    if train_scores is None:
        images_list.append(SimpleNamespace(image=images[i]))
    else:
        images_list.append(SimpleNamespace(image=images[i],
                                           train_scores=train_scores[i]))
images_list = sorted(images_list, key=lambda x: x.train_scores)

In [6]:
images_list

[namespace(image=[1], train_scores=1),
 namespace(image=[3, 4], train_scores=2),
 namespace(image=[8, 8, 8], train_scores=3),
 namespace(image=[5, 8, 7, 3], train_scores=4),
 namespace(image=[1, 2, 3, 4, 5], train_scores=5),
 namespace(image=[1, 0, 2, 93, 4, 5], train_scores=6),
 namespace(image=[5, 4, 3, 2, 5, 3, 4], train_scores=7)]

In [7]:
ds = images_list[1]

In [8]:
ds

namespace(image=[3, 4], train_scores=2)

In [9]:
ds.image

[3, 4]

In [10]:
ds.train_scores

2

In [11]:
imgs =  O.DataHelper.get2D(N=10)

DataLoader type is:  <class 'omama.loaders.omama_loader.OmamaLoader'>


In [12]:
imgs

[namespace(filePath='/raid/data01/deephealth/dh_dcm_ast/2.25.100000201839274263174475898571171534853/DXm.2.25.119403010146292111130118207990186551199',
           SOPInstanceUID='2.25.119403010146292111130118207990186551199',
           StudyInstanceUID='2.25.100000201839274263174475898571171534853',
           PatientID='DHJ5JE9QXAV0',
           InstanceNumber="2",
           label='NonCancer',
           imageLaterality='L',
           shape=(3062, 2394),
           metadata=None,
           pixels=array([[   0,    0,    0, ...,    0,    0,    0],
                         [   0,    0,    0, ...,    0,    0,    0],
                         [   0,    0,    0, ...,    0,    0,    0],
                         ...,
                         [3043, 3089, 3066, ...,    0,    0,    0],
                         [3083, 3055, 3078, ...,    0,    0,    0],
                         [3117, 3123, 3155, ...,    0,    0,    0]], dtype=uint16)),
 namespace(filePath='/raid/data01/deephealth/dh_dcm_ast/

In [13]:
ts = [5,2,77,6,4,3,6,2,11,23]

In [14]:
image_list = []
for i in range(len(imgs)):
    image_list.append(SimpleNamespace(image=imgs[i],
                                           score=ts[i]))
image_list = sorted(image_list, key=lambda x: x.score, reverse=True)

In [15]:
image_list

[namespace(image=namespace(filePath='/raid/data01/deephealth/dh_dcm_ast/2.25.100001373726337750354689693677327988604/DXm.2.25.275395047981175631229220204776148301030',
                           SOPInstanceUID='2.25.275395047981175631229220204776148301030',
                           StudyInstanceUID='2.25.100001373726337750354689693677327988604',
                           PatientID='DHHH0JGQENU9',
                           InstanceNumber="2",
                           label='NonCancer',
                           imageLaterality='L',
                           shape=(3062, 2394),
                           metadata=None,
                           pixels=array([[3, 5, 5, ..., 0, 0, 0],
                                         [3, 6, 8, ..., 0, 0, 0],
                                         [5, 5, 4, ..., 0, 0, 0],
                                         ...,
                                         [3, 4, 6, ..., 0, 0, 0],
                                         [4, 7, 8, ..., 0

In [16]:
len(image_list)

10

In [17]:
type(image_list[0].image.filePath)

str

In [18]:
type(imgs[0])

types.SimpleNamespace

In [19]:
pixels = []
for img in imgs:
    pixels.append(img.pixels)

In [20]:
type(pixels)

list

In [21]:
normalized_pixels = []
for p in pixels:
    max_val = np.max(p)
    min_val = np.min(p)
    temp_pixels = p.astype(np.float32).copy()
    temp_pixels -= min_val
    temp_pixels /= (max_val - min_val)
    temp_pixels *= 255
    normalized_pixels.append(temp_pixels)

In [22]:
normalized_pixels[0]

array([[  0.     ,   0.     ,   0.     , ...,   0.     ,   0.     ,
          0.     ],
       [  0.     ,   0.     ,   0.     , ...,   0.     ,   0.     ,
          0.     ],
       [  0.     ,   0.     ,   0.     , ...,   0.     ,   0.     ,
          0.     ],
       ...,
       [189.49084, 192.35532, 190.92308, ...,   0.     ,   0.     ,
          0.     ],
       [191.98169, 190.2381 , 191.67033, ...,   0.     ,   0.     ,
          0.     ],
       [194.0989 , 194.47253, 196.46521, ...,   0.     ,   0.     ,
          0.     ]], dtype=float32)

In [23]:
type(normalized_pixels)

list

In [24]:
for i in range(len(normalized_pixels)):
    print(normalized_pixels[i].shape)

(3062, 2394)
(2294, 1914)
(3062, 2394)
(3062, 2394)
(2294, 1914)
(3062, 2394)
(3062, 2394)
(2294, 1914)
(2294, 1914)
(2294, 1914)


In [25]:
from skimage.feature import SIFT

In [26]:
kwargs = {}
upsampling = kwargs.get('upsampling', 1)
n_octaves = kwargs.get('n_octaves', 1)
n_scales = kwargs.get('n_scales', 1)
sigma_min = kwargs.get('sigma_min', 1.3)
sigma_in = kwargs.get('sigma_in', .5)
c_dog = kwargs.get('c_dog', .7)
c_edge = kwargs.get('c_edge', .05)
n_bins = kwargs.get('n_bins', 10)
lambda_ori = kwargs.get('lambda_ori', .5)
c_max = kwargs.get('c_max', 1.5)
lambda_descr = kwargs.get('lambda_descr', .5)
n_hist = kwargs.get('n_hist', 1)
n_ori = kwargs.get('n_ori', 1)

In [27]:
descriptor_extractor = SIFT(upsampling=upsampling,
                            n_octaves=n_octaves,
                            n_scales=n_scales,
                            sigma_min=sigma_min,
                            sigma_in=sigma_in,
                            c_dog=c_dog,
                            c_edge=c_edge,
                            n_bins=n_bins,
                            lambda_ori=lambda_ori,
                            c_max=c_max,
                            lambda_descr=lambda_descr,
                            n_hist=n_hist,
                            n_ori=n_ori)


In [68]:
keypoints = []
if isinstance(normalized_pixels, list) or isinstance(normalized_pixels, np.ndarray):
    for i in range(len(normalized_pixels)):
        print(normalized_pixels[i].shape)
        descriptor_extractor.detect_and_extract(normalized_pixels[i])
        keypoints.append(descriptor_extractor.keypoints)
else:
    print("in the else statement")
    descriptor_extractor.detect_and_extract(normalized_pixels)
    keypoints.append(descriptor_extractor.keypoints)

(3062, 2394)
(2294, 1914)
(3062, 2394)
(3062, 2394)
(2294, 1914)
(3062, 2394)
(3062, 2394)
(2294, 1914)
(2294, 1914)
(2294, 1914)


In [44]:
keypoints[9]

array([[ 298,   11],
       [ 299,   15],
       [ 333,    6],
       [ 345,   50],
       [ 384,  169],
       [ 384,  170],
       [ 387,   68],
       [ 391,  183],
       [ 394,   81],
       [ 396,  193],
       [ 402,  203],
       [ 416,  226],
       [ 416,  120],
       [ 432,  136],
       [ 435,  189],
       [ 436, 1527],
       [ 436, 1527],
       [ 439, 1575],
       [ 442, 1569],
       [ 464,    7],
       [ 467,  147],
       [ 468,   20],
       [ 476,   90],
       [ 476,  142],
       [ 479, 1504],
       [ 483, 1575],
       [ 481, 1645],
       [ 484, 1574],
       [ 488, 1633],
       [ 493,  127],
       [ 497,  180],
       [ 502, 1529],
       [ 509, 1536],
       [ 510,   12],
       [ 515, 1621],
       [ 523,  193],
       [ 536, 1702],
       [ 541, 1613],
       [ 548, 1598],
       [ 555, 1697],
       [ 559,   34],
       [ 563, 1618],
       [ 563,  124],
       [ 563,  305],
       [ 566,  149],
       [ 572,  159],
       [ 573, 1627],
       [ 577,

In [70]:
intensities = []
for i in range(len(keypoints)):
    intensities.append(
        O.Features._extract_pixel_intensity_from_keypoints(
            keypoints[i], pixels[i]))

type of intensities: <class 'list'>
type of intensities: <class 'list'>
type of intensities: <class 'list'>
type of intensities: <class 'list'>
type of intensities: <class 'list'>
type of intensities: <class 'list'>
type of intensities: <class 'list'>
type of intensities: <class 'list'>
type of intensities: <class 'list'>
type of intensities: <class 'list'>


In [66]:
type(intensities)

list

In [34]:
from skimage.feature import ORB

In [35]:
downsampled_images = O.Normalize.downsample(pixels, output_shape=(256,256))[0]

In [36]:
downsampled_images[0].shape

(256, 256)

In [37]:
norm_imgs = O.Normalize.get_norm(downsampled_images, norm_type='minmax')[0]

In [48]:
norm_imgs[0].shape

(256, 256)

In [39]:
kwargs = {}
n_keypoints = kwargs.get('n_keypoints', 50)
fast_n = kwargs.get('fast_n', 9)
fast_threshold = kwargs.get('fast_threshold', 0.08)
harris_k = kwargs.get('harris_k', 0.04)
downscale = kwargs.get('downscale', 1.2)
n_scales = kwargs.get('n_scales', 8)


In [40]:
descriptor_extractor_orb = ORB(n_keypoints=n_keypoints,
                               fast_n=fast_n,
                               fast_threshold=fast_threshold,
                               harris_k=harris_k,
                               downscale=downscale,
                               n_scales=n_scales)


In [51]:
keypoints2 = []
if isinstance(norm_imgs, list) or isinstance(norm_imgs, np.ndarray):
    for i in range(len(norm_imgs)):
        print(norm_imgs[i].shape)
        descriptor_extractor_orb.detect_and_extract(norm_imgs[i])
        keypoints2.append(descriptor_extractor_orb.keypoints)
else:
    print("in the else statement")
    descriptor_extractor_orb.detect_and_extract(norm_imgs)
    keypoints2.append(descriptor_extractor_orb.keypoints)

(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)
(256, 256)


In [52]:
keypoints2[9]

array([[ 54.     , 196.8    ],
       [ 54.74304, 201.55392],
       [ 54.     , 196.     ],
       [ 44.928  , 205.632  ],
       [ 44.64   , 204.48   ],
       [ 57.     , 232.     ],
       [ 45.6192 , 205.2864 ],
       [ 44.     , 203.     ],
       [ 53.9136 , 201.1392 ],
       [ 53.568  , 200.448  ],
       [ 68.     , 225.     ],
       [ 44.4    , 204.     ],
       [ 53.28   , 198.72   ],
       [ 67.68   , 226.08   ],
       [ 57.6    , 231.6    ],
       [ 67.2    , 225.6    ],
       [ 56.     , 210.     ],
       [ 56.     , 217.     ],
       [ 60.     , 220.     ],
       [ 55.2    , 217.2    ],
       [ 55.2    , 211.2    ],
       [ 54.     , 205.     ],
       [ 55.296  , 214.272  ],
       [ 60.     , 222.     ],
       [ 52.     , 213.     ],
       [ 54.72   , 213.12   ],
       [ 52.8    , 213.6    ],
       [ 52.     , 202.     ],
       [ 58.752  , 224.64   ],
       [ 59.04   , 223.2    ],
       [ 52.8    , 204.     ],
       [ 57.     , 223.     ],
       [

In [53]:
intensities2 = []
for i in range(len(keypoints2)):
    intensities2.append(
        O.Features._extract_pixel_intensity_from_keypoints(
            keypoints2[i], norm_imgs[i]))

In [59]:
print(type(intensities[0]))
print(type(intensities2[0]))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [60]:
print(intensities[0].shape)
print(intensities2[0].shape)

(182,)
(50,)


In [61]:
keypoints = intensities

In [63]:
keypoints

[array([2324, 2344, 2341, 2321, 2340, 2319, 2652, 2345, 2702, 2296, 2345,
        2303, 2345, 3025, 2789, 3108, 2755, 2726, 3155, 3118, 3063, 2697,
        2567, 2828, 3104, 3085, 2989, 3008, 2922, 2882, 3209, 3077, 3112,
        2979, 2947, 2826, 3078, 2937, 3026, 2730, 2657, 2961, 3193, 2946,
        2908, 3058, 2973, 3095, 3275, 2901, 2898, 3025, 2735, 2914, 3064,
        2962, 3109, 3086, 3035, 3109, 3028, 3086, 3143, 3153, 3093, 2742,
        2901, 2678, 3052, 2743, 2730, 2977, 2610, 3073, 2952, 2948, 2998,
        2939, 3083, 3068, 2853, 2827, 3020, 3032, 2969, 3160, 3070, 3046,
        3069, 2730, 2668, 3016, 2982, 2710, 3002, 3106, 2720, 2919, 3146,
        3216, 2716, 2734, 3086, 2798, 3112, 2925, 2791, 2978, 2701, 2985,
        2942, 2893, 2984, 2948, 3095, 2982, 2710, 2699, 2668, 2718, 2826,
        2660, 2667, 3000, 2908, 2732, 3087, 2892, 2813, 3143, 2919, 3151,
        2775, 2534, 2887, 2673, 3153, 2232, 2996, 2904, 2890, 1713, 3251,
        3243, 2145, 3733, 3352, 2076, 