In [3]:
%pylab inline
%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
import sys
sys.path.insert(0,'../..')
import omama as O
from skimage.transform import resize

In [5]:
odl = O.OutlierDetectorLite()

In [6]:
data = odl.load_data("A")

In [7]:
pixels = O.Normalize.extract_pixels(data)

In [8]:
type(pixels[0])

numpy.ndarray

In [9]:
pixels[:2]

[array([[   0,    0,    0, ..., 2429, 2430, 2443],
        [   0,    0,    0, ..., 2420, 2446, 2457],
        [   0,    0,    0, ..., 2444, 2461, 2454],
        ...,
        [   0,    0,    0, ..., 2481, 2505, 2536],
        [   0,    0,    0, ..., 2494, 2521, 2527],
        [   0,    0,    0, ..., 2510, 2525, 2541]], dtype=uint16),
 array([[ 104,  100,  100, ..., 2828, 2738, 2741],
        [ 107,  100,  103, ..., 2810, 2745, 2731],
        [ 103,   99,  101, ..., 2753, 2765, 2748],
        ...,
        [ 105,  104,  105, ..., 2590, 2563, 2567],
        [ 107,  108,  106, ..., 2585, 2565, 2577],
        [ 104,  104,  101, ..., 2581, 2568, 2562]], dtype=uint16)]

In [61]:
resized = []
for p in pixels:
    resized.append(np.array(resize(p, (256,256))).reshape(-1))

In [62]:
resized[:2]

[array([0.        , 0.        , 0.        , ..., 0.03895602, 0.03768494,
        0.03796986]),
 array([0.00152881, 0.00154785, 0.0015675 , ..., 0.03832124, 0.03867875,
        0.03945722])]

In [52]:
resized[:2]

[array([0.        , 0.        , 0.        , ..., 0.03895602, 0.03768494,
        0.03796986]),
 array([0.00152881, 0.00154785, 0.0015675 , ..., 0.03832124, 0.03867875,
        0.03945722])]

In [53]:
resized = np.asarray(resized)

In [54]:
resized.shape

(100, 65536)

In [55]:
for i in range(len(resized)):
    resized[i] = O.Normalize.get_norm(resized[i], 'minmax')[0]    

In [56]:
resized[0]

array([  0.        ,   0.        ,   0.        , ..., 176.70581055,
       170.94015503, 172.23258972])

In [57]:
resized[0].shape

(65536,)

In [58]:
resized = np.asarray(resized)

In [59]:
type(resized)

numpy.ndarray

In [60]:
resized.shape

(100, 65536)