In [1]:
%pylab inline
%load_ext autoreload
%autoreload 2
import omama as O

Populating the interactive namespace from numpy and matplotlib


In [1]:
import pydicom as dicom

In [2]:
ds = dicom.dcmread("/raid/data01/deephealth/dh_dh0new/2.25.270894907573695502794115375476585077379/BT.2.25.95276871100665437640665785293808078818")

In [3]:



print(int(ds.HighBit), int(ds.Rows), int(ds.Columns))

9 2457 1890


In [4]:
ds.get("PatientAge")

''

In [5]:
ds.get("SOPInstanceUID")

'2.25.95276871100665437640665785293808078818'

In [6]:
ds.get("StudyInstanceUID")

'2.25.270894907573695502794115375476585077379'

In [7]:
ds.get("Modality")

'MG'

In [8]:
ds.get("PatientSex")

''

In [9]:
ds.get("Manufacturer")

'HOLOGIC, Inc.'

In [10]:
ds.get("ManufacturerModelName")

'Selenia Dimensions'

In [11]:
ds.get("NumberOfFrames")

'84'

In [12]:
ds.get("SharedFunctionalGroupsSequence")

<Sequence, length 1>

In [13]:
ds.get("Rows")

2457

In [14]:
ds.get("Columns")

1890

In [16]:
ds.get("SliceLocation")

In [17]:
print("hee")

hee


In [2]:
data = O.Data(timing = True)

dfs...took  0.6509122848510742 seconds
studies...took  0.5763950347900391 seconds
seriesCount...took  3.337860107421875e-06 seconds
dicoms...took  20.567142724990845 seconds
loadImages...took  4.884752988815308 seconds
stats...took  2.3603439331054688e-05 seconds
__init__...took  26.680704593658447 seconds


In [3]:
data.getLabel(studyInstanceUID = '2.25.100000201839274263174475898571171534853', imageLaterality = 'None', timing = True)

'NonCancer'

In [4]:
data.stats

{'folder0': {'total': 819387,
  '3D': 58,
  '2D': 819329,
  'label_2D': None,
  'labels_3D': None},
 'folder1': {'total': 126460,
  '3D': 62736,
  '2D': 63724,
  'label_2D': None,
  'labels_3D': None},
 'folder2': {'total': 22144,
  '3D': 9363,
  '2D': 12781,
  'label_2D': None,
  'labels_3D': None},
 'total_dicoms   ': 967991,
 'total_2D_dicoms': 895834,
 'total_3D_dicoms': 72157}

In [5]:
obj1 = data.get_study(StudyInstanceUID = '2.25.107458203119551477163066266617500324368', verbose = True, timing = True)

...took  0.00012063980102539062 seconds


In [13]:
data.getFileNamesInSeries('2.25.10195843533591784827173654674484223783')

['DXm.2.25.194802732246376664452614854779373953824',
 'DXm.2.25.17209614847888714130951474939713442064',
 'DXm.2.25.57630566928077326371238348183387955226',
 'DXm.2.25.197478861361651443524663676575442774649',
 'BT.2.25.105578318005441312625678019845776956270']

In [6]:
data.files_3D[0]

'/raid/data01/deephealth/dh_dcm_ast/2.25.10195843533591784827173654674484223783/BT.2.25.105578318005441312625678019845776956270'

In [14]:
data.get_image(Dicom_ID = data.get_study(StudyInstanceUID='2.25.10195843533591784827173654674484223783').images[0],pixels = False, dicom_header=True )

/raid/data01/deephealth/dh_dcm_ast/2.25.10195843533591784827173654674484223783/DXm.2.25.194802732246376664452614854779373953824


TypeError: Could not convert value to integer without loss

In [15]:
obj2 = data.get_study(ID = 4566, verbose = True, timing = True)

...took  0.00013780593872070312 seconds


In [16]:
len(data.files_2D)

895834

In [17]:
len(data.files_3D)

72157

In [18]:
obj2

namespace(directory='/raid/data01/deephealth/dh_dcm_ast/2.25.107458203119551477163066266617500324368',
          Study_ID=4566,
          UID='2.25.107458203119551477163066266617500324368',
          images=['DXm.2.25.242491002112160262982899137223275866675',
                  'DXm.2.25.225261049996665895658685451583431562831',
                  'DXm.2.25.106933344606876712529416924215791884636',
                  'DXm.2.25.235058324317194583860381035396839335391'],
          info={'total': 4, '3D count': 0, '2D count': 4})

In [19]:
data.get_study(ID = 4566, verbose = True, timing = True).images[0]

...took  9.870529174804688e-05 seconds


'DXm.2.25.242491002112160262982899137223275866675'

In [20]:
data.get_image(Dicom_ID = data.get_study(ID = 4566).images[0])

/raid/data01/deephealth/dh_dcm_ast/2.25.107458203119551477163066266617500324368/DXm.2.25.242491002112160262982899137223275866675


(array([[ 277,  273,  274, ..., 3164, 3158, 3106],
        [ 280,  278,  275, ..., 3226, 3209, 3155],
        [ 279,  279,  275, ..., 3189, 3160, 3189],
        ...,
        [ 340,  338,  341, ..., 2638, 2668, 2705],
        [ 343,  343,  341, ..., 2652, 2684, 2721],
        [ 343,  341,  337, ..., 2666, 2692, 2730]], dtype=uint16),
 {'label': 'NonCancer',
  'filePath': '/raid/data01/deephealth/dh_dcm_ast/2.25.107458203119551477163066266617500324368/DXm.2.25.242491002112160262982899137223275866675',
  'shape': (2294, 1914),
  'metadata': None})

In [22]:
data.getImageID('BT.2.25.105578318005441312625678019845776956270')

5503

In [23]:
data.master_dict_idx[5503]

{'UID': '2.25.108991809389751259733186104144175249642',
 'path': '/raid/data01/deephealth/dh_dcm_ast/'}

In [26]:
data.master_dict_uid['2.25.108991809389751259733186104144175249642']['Study_ID']

5503

In [27]:
data.images[5503]

'/raid/data01/deephealth/dh_dcm_ast/2.25.10195843533591784827173654674484223783/BT.2.25.105578318005441312625678019845776956270'

In [28]:
data.get_image(Dicom_ID = data.get_study(ID = 5503).images[0])

/raid/data01/deephealth/dh_dcm_ast/2.25.108991809389751259733186104144175249642/DXm.2.25.59449656187990973228813403432939179318


(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 {'label': 'NonCancer',
  'filePath': '/raid/data01/deephealth/dh_dcm_ast/2.25.108991809389751259733186104144175249642/DXm.2.25.59449656187990973228813403432939179318',
  'shape': (4096, 3328),
  'metadata': None})

In [39]:
data.files_3D

['/raid/data01/deephealth/dh_dcm_ast/2.25.10195843533591784827173654674484223783/BT.2.25.105578318005441312625678019845776956270',
 '/raid/data01/deephealth/dh_dcm_ast/2.25.127778741107585459212101461672817162529/BT.2.25.18192988146053266384291124747312171363',
 '/raid/data01/deephealth/dh_dcm_ast/2.25.127778741107585459212101461672817162529/BT.2.25.221685859022887549299160176881055562610',
 '/raid/data01/deephealth/dh_dcm_ast/2.25.127778741107585459212101461672817162529/BT.2.25.276864501342113860487720551376804139651',
 '/raid/data01/deephealth/dh_dcm_ast/2.25.127778741107585459212101461672817162529/BT.2.25.59937235060272841519365064740166485018',
 '/raid/data01/deephealth/dh_dcm_ast/2.25.205977105373834904482549943110025903884/BT.2.25.189385738374386252581394140984961417822',
 '/raid/data01/deephealth/dh_dcm_ast/2.25.205977105373834904482549943110025903884/BT.2.25.215556154105815500888404807837859572737',
 '/raid/data01/deephealth/dh_dcm_ast/2.25.2059771053738349044825499431100259038

In [7]:
data.getFileNamesInSeries('2.25.270894907573695502794115375476585077379')

['DXm.2.25.263589489743102209653900284902780355940',
 'BT.2.25.320803805530927902146651217259409640803',
 'BT.2.25.7720140520784864464568534244294918850',
 'DXm.2.25.22275769620904985302143148250499798631',
 'BT.2.25.95276871100665437640665785293808078818',
 'DXm.2.25.25684291526133087394952373583472107657',
 'DXm.2.25.314506286437510905192375129856965486520',
 'BT.2.25.83314214933756453744420078155848946587']

In [15]:
data.get_image(Dicom_ID = data.get_study('2.25.270894907573695502794115375476585077379').images[4], pixels = False, dicom_header=False)

/raid/data01/deephealth/dh_dh0new/2.25.270894907573695502794115375476585077379/BT.2.25.95276871100665437640665785293808078818


(None,
 {'label': 'NonCancer',
  'file Path': '/raid/data01/deephealth/dh_dh0new/2.25.270894907573695502794115375476585077379/BT.2.25.95276871100665437640665785293808078818',
  'shape': (84, 2457, 1890),
  'metadata': None})

In [32]:
data.get_image(Image_ID = 20006, pixels = False)

(None,
 {'label': 'NonCancer',
  'file Path': '/raid/data01/deephealth/dh_dcm_ast/2.25.107458203119551477163066266617500324368/DXm.2.25.242491002112160262982899137223275866675',
  'shape': (2294, 1914),
  'metadata': None})

In [33]:
data.get_image(path = '/raid/data01/deephealth/dh_dcm_ast/2.25.107458203119551477163066266617500324368/DXm.2.25.242491002112160262982899137223275866675')

(array([[ 277,  273,  274, ..., 3164, 3158, 3106],
        [ 280,  278,  275, ..., 3226, 3209, 3155],
        [ 279,  279,  275, ..., 3189, 3160, 3189],
        ...,
        [ 340,  338,  341, ..., 2638, 2668, 2705],
        [ 343,  343,  341, ..., 2652, 2684, 2721],
        [ 343,  341,  337, ..., 2666, 2692, 2730]], dtype=uint16),
 {'label': 'NonCancer',
  'file Path': '/raid/data01/deephealth/dh_dcm_ast/2.25.107458203119551477163066266617500324368/DXm.2.25.242491002112160262982899137223275866675',
  'shape': (2294, 1914),
  'metadata': None})

In [37]:
data.get_image(Dicom_ID = data.get_study(ID = 17777, verbose = True, timing = True).images[0],pixels = False, dicom_header = True)

...took  0.0001251697540283203 seconds


(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 {'label': 'NonCancer',
  'file Path': '/raid/data01/deephealth/dh_dcm_ast/2.25.129335442227068568810348451719621137663/DXm.2.25.293759476561243643522581083011922347805',
  'shape': (4096, 3328),
  'metadata': Dataset.file_meta -------------------------------
  (0002, 0000) File Meta Information Group Length  UL: 192
  (0002, 0001) File Meta Information Version       OB: b'\x00\x01'
  (0002, 0002) Media Storage SOP Class UID         UI: Digital Mammography X-Ray Image Storage - For Presentation
  (0002, 0003) Media Storage SOP Instance UID      UI: 2.25.293759476561243643522581083011922347805
  (0002, 0010) Transfer Syntax UID                 UI: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1])
  (0002, 0012) Implementation

In [47]:
len(data.files_3D_per_study[0])

58

In [6]:
data.files_3D_per_study[1]

['/raid/data01/deephealth/dh_dh0new/2.25.270894907573695502794115375476585077379/BT.2.25.320803805530927902146651217259409640803',
 '/raid/data01/deephealth/dh_dh0new/2.25.270894907573695502794115375476585077379/BT.2.25.7720140520784864464568534244294918850',
 '/raid/data01/deephealth/dh_dh0new/2.25.270894907573695502794115375476585077379/BT.2.25.95276871100665437640665785293808078818',
 '/raid/data01/deephealth/dh_dh0new/2.25.270894907573695502794115375476585077379/BT.2.25.83314214933756453744420078155848946587',
 '/raid/data01/deephealth/dh_dh0new/2.25.338822672101717465481000627910583793627/BT.2.25.207254167834517633248107903952085708624',
 '/raid/data01/deephealth/dh_dh0new/2.25.338822672101717465481000627910583793627/BT.2.25.188709856063728062642198046839000166804',
 '/raid/data01/deephealth/dh_dh0new/2.25.338822672101717465481000627910583793627/BT.2.25.100275026317800611025489961394122613111',
 '/raid/data01/deephealth/dh_dh0new/2.25.338822672101717465481000627910583793627/BT.2.2

In [41]:
len(data.files_3D_per_study[1])

62736

In [42]:
len(data.files_3D_per_study[2])

9363

In [43]:
len(data.files_2D_per_study[0])

819329

In [44]:
len(data.files_2D_per_study[1])

63724

In [45]:
len(data.files_2D_per_study[2])

12781

In [46]:
data.files_2D_per_study[2]

['/raid/data01/deephealth/dh_dh2/2.25.304937867007350960833525283221291868496/DXm.2.25.163253663577850469217022856660968835387',
 '/raid/data01/deephealth/dh_dh2/2.25.304937867007350960833525283221291868496/DXm.2.25.181917781836205183906152904076673929371',
 '/raid/data01/deephealth/dh_dh2/2.25.304937867007350960833525283221291868496/DXm.2.25.263039212383111738334796774720096236827',
 '/raid/data01/deephealth/dh_dh2/2.25.304937867007350960833525283221291868496/DXm.2.25.302502594378252845065683692816750884818',
 '/raid/data01/deephealth/dh_dh2/2.25.304937867007350960833525283221291868496/DXm.2.25.250009440415950110977593847158734431368',
 '/raid/data01/deephealth/dh_dh2/2.25.304937867007350960833525283221291868496/DXm.2.25.324110147453454074574706273668956516253',
 '/raid/data01/deephealth/dh_dh2/2.25.304937867007350960833525283221291868496/DXm.2.25.64457130315592681933641195809476834974',
 '/raid/data01/deephealth/dh_dh2/2.25.304937867007350960833525283221291868496/DXm.2.25.63739345265