In [1]:
%pylab inline
%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib


In [2]:
import sys
import time
sys.path.insert(0,'../..')
import omama as O
from skimage.feature import (match_descriptors, corner_harris,
                             corner_peaks, ORB, plot_matches)

In [5]:
descriptor_extractor = ORB(n_keypoints=200)

In [6]:
pixels = []
for img in imgs:
    pixels.append(img.pixels)

In [9]:
downsized_img1 = O.Normalize.downsample(imgs, normalize=True)

Downsampling images to shape: None
Downsampling 10 images
Normalizing images in downsampling
minmax: not list
minmax: not list
minmax: not list
minmax: not list
minmax: not list
minmax: not list
minmax: not list
minmax: not list
minmax: not list
minmax: not list


In [10]:
downsized_img1[0].shape


(128, 128)

In [11]:
descriptor_extractor = ORB(n_keypoints=50)

In [12]:
discriptors = []

for item in downsized_img1:
    descriptor_extractor.detect_and_extract(item)
    kp = descriptor_extractor.keypoints
#     dex = descriptor_extractor.detect_and_extract(item)
#     kp = descriptor_extractor.keypoints
    
    discriptors.append(kp)


In [13]:
discriptors

[array([[67.18464, 57.23136],
        [67.392  , 57.024  ],
        [66.3552 , 55.9872 ],
        [90.     , 29.     ],
        [67.2    , 48.     ],
        [64.     , 41.     ],
        [65.     , 51.     ],
        [89.     , 34.     ],
        [57.     , 41.     ],
        [56.     , 35.     ],
        [90.     , 28.8    ],
        [88.     , 37.     ],
        [90.     , 34.8    ],
        [67.392  , 48.384  ],
        [61.2    , 42.     ],
        [91.     , 32.     ],
        [67.68   , 47.52   ],
        [55.2    , 31.2    ],
        [67.     , 47.     ],
        [57.6    , 40.8    ],
        [71.     , 50.     ],
        [90.72   , 28.8    ],
        [55.     , 31.     ],
        [65.     , 28.     ],
        [61.92   , 43.2    ],
        [87.     , 35.     ],
        [83.     , 37.     ],
        [74.     , 44.     ],
        [56.16   , 31.68   ],
        [64.8    , 27.6    ],
        [63.6    , 40.8    ],
        [88.     , 27.     ],
        [88.     , 21.     ],
        [9

In [14]:
kp_intensitites = O.KeyPointIntensities(images=imgs, keypoints=discriptors, algorithm="orb")

kp:  67 57
kp:  67 57
kp:  66 55
kp:  90 29
kp:  67 48
kp:  64 41
kp:  65 51
kp:  89 34
kp:  57 41
kp:  56 35
kp:  90 28
kp:  88 37
kp:  90 34
kp:  67 48
kp:  61 42
kp:  91 32
kp:  67 47
kp:  55 31
kp:  67 47
kp:  57 40
kp:  71 50
kp:  90 28
kp:  55 31
kp:  65 28
kp:  61 43
kp:  87 35
kp:  83 37
kp:  74 44
kp:  56 31
kp:  64 27
kp:  63 40
kp:  88 27
kp:  88 21
kp:  90 34
kp:  84 41
kp:  74 32
kp:  93 30
kp:  82 37
kp:  52 32
kp:  57 40
kp:  52 28
kp:  83 37
kp:  68 38
kp:  84 40
kp:  67 41
kp:  64 41
kp:  53 33
kp:  67 40
kp:  45 28
kp:  87 38
kp:  64 66
kp:  63 65
kp:  64 67
kp:  65 68
kp:  63 64
kp:  64 66
kp:  59 68
kp:  63 65
kp:  58 68
kp:  69 67
kp:  59 69
kp:  69 66
kp:  70 67
kp:  58 69
kp:  70 67
kp:  58 68
kp:  70 66
kp:  71 87
kp:  55 79
kp:  56 76
kp:  57 75
kp:  59 80
kp:  60 80
kp:  63 77
kp:  75 81
kp:  53 79
kp:  54 83
kp:  58 80
kp:  43 94
kp:  64 77
kp:  58 81
kp:  55 85
kp:  56 79
kp:  70 86
kp:  66 95
kp:  44 98
kp:  43 94
kp:  75 79
kp:  53 84
kp:  41 95
kp:  77 87

In [15]:
kp_intensitites.intensities()

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32),
 array([39., 37., 39., 43., 40., 37., 39., 38., 38., 36., 40., 41., 36.,
        43., 38., 38., 39., 41., 38., 42., 39., 40., 41., 39., 41., 41.,
        41., 41., 40., 42., 39., 41., 39., 39., 41., 39., 39., 41., 40.,
        40., 41., 39., 41., 39., 40., 39., 38., 40., 41., 40.],
       dtype=float32),
 array([31., 37., 36., 36., 34., 35., 33., 29., 32., 34., 33., 34., 30.,
        32., 35., 25., 36., 35., 35., 35., 30., 34., 33., 34., 37., 33.,
        29., 32., 34., 34., 33., 36., 34., 37., 29., 34., 36., 36., 35.,
        35., 27., 31., 33., 34., 34., 33., 27., 25., 34., 37.],
       dtype=float32),
 array([27., 29., 26., 25., 33., 29., 28., 23., 34.,  6., 29., 27., 28.,
        33., 35., 26., 30., 28., 25.,  8., 26., 29., 23., 30., 26.,

In [17]:
kp_intensitites.get_data(2)

('2.25.275395047981175631229220204776148301030',
 array([[3, 5, 5, ..., 0, 0, 0],
        [3, 6, 8, ..., 0, 0, 0],
        [5, 5, 4, ..., 0, 0, 0],
        ...,
        [3, 4, 6, ..., 0, 0, 0],
        [4, 7, 8, ..., 0, 0, 0],
        [8, 8, 9, ..., 0, 0, 0]], dtype=uint16),
 array([[67.68   , 82.08   ],
        [68.     , 82.     ],
        [67.2    , 81.6    ],
        [67.392  , 81.216  ],
        [68.4288 , 80.8704 ],
        [69.67296, 82.11456],
        [78.     , 62.     ],
        [71.     , 69.     ],
        [71.     , 72.     ],
        [78.     , 62.4    ],
        [92.     , 49.     ],
        [74.     , 62.     ],
        [80.     , 48.     ],
        [74.     , 56.     ],
        [74.     , 72.     ],
        [74.4    , 72.     ],
        [50.4    , 60.     ],
        [50.     , 60.     ],
        [77.     , 69.     ],
        [55.2    , 30.     ],
        [69.12   , 48.384  ],
        [51.84   , 60.48   ],
        [79.2    , 63.36   ],
        [51.6    , 27.6    ],
    